/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/core/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => MindMapPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");

// src/shared/types.ts
var VIEW_TYPE_MIND_MAP = "obsimap-view";
var DEFAULT_SETTINGS = {
  exportFolder: "",
  theme: "default",
  hotkeys: {
    addChild: "Tab",
    addSibling: "Enter",
    delete: "Delete",
    rename: "Shift+Enter",
    reorderUp: "Shift+ArrowUp",
    reorderDown: "Shift+ArrowDown",
    promote: "Shift+ArrowLeft",
    demote: "Shift+ArrowRight",
    searchNote: "Shift+Ctrl+Enter",
    createNote: "Ctrl+Shift+N",
    openNote: "Ctrl+Shift+L",
    toggleCollapse: "Ctrl+/"
  },
  stripMetadata: true,
  showHoverPreview: true,
  maxNodeLength: 20,
  nodeStyle: "pill"
};

// src/core/main.ts
var MindMapPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.isInternalRenaming = false;
  }
  async onload() {
    await this.loadSettings();
    this.registerView(
      VIEW_TYPE_MIND_MAP,
      (leaf) => new MindMapView(leaf, this)
    );
    this.registerExtensions(["mindmap"], VIEW_TYPE_MIND_MAP);
    this.addRibbonIcon("network", "Open mind map", () => {
      void this.activateView();
    });
    this.addSettingTab(new MindMapSettingTab(this.app, this));
    this.addCommand({
      id: "import-markdown",
      name: "Import current note",
      callback: () => {
        const leaves = this.app.workspace.getLeavesOfType(VIEW_TYPE_MIND_MAP);
        const view = leaves.length > 0 ? leaves[0].view : null;
        if (view instanceof MindMapView) {
          void view.importMarkdown();
        } else {
          void this.activateView().then(() => {
            const newLeaves = this.app.workspace.getLeavesOfType(VIEW_TYPE_MIND_MAP);
            const newView = newLeaves.length > 0 ? newLeaves[0].view : null;
            if (newView instanceof MindMapView)
              void newView.importMarkdown();
          });
        }
      }
    });
    this.registerEvent(
      this.app.vault.on("rename", (file, oldPath) => {
        if (this.isInternalRenaming)
          return;
        if (file instanceof import_obsidian.TFile && (file.extension === "md" || file.extension === "mindmap")) {
          void this.handleFileRename(file, oldPath);
        }
      })
    );
    this.registerEvent(
      this.app.workspace.on("active-leaf-change", (leaf) => {
        if (leaf && leaf.view instanceof MindMapView) {
          leaf.view.focusContainer();
        }
      })
    );
  }
  async loadSettings() {
    const data = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, data);
    if (data && data.hotkeys) {
      this.settings.hotkeys = Object.assign({}, DEFAULT_SETTINGS.hotkeys, data.hotkeys);
    }
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async handleFileRename(file, oldPath) {
    const oldFileObj = this.getOldFileData(oldPath);
    const newName = file.basename;
    const oldName = oldFileObj.basename;
    if (oldName === newName)
      return;
    const mindmapFiles = this.app.vault.getFiles().filter((f) => f.extension === "mindmap");
    for (const mmFile of mindmapFiles) {
      let content = await this.app.vault.read(mmFile);
      const oldLinkRegex = new RegExp(`\\[\\[${this.escapeRegExp(oldName)}(\\|[^\\]]+)?\\]\\]`, "g");
      if (content.match(oldLinkRegex)) {
        const updatedContent = content.replace(oldLinkRegex, (match, alias) => {
          return alias ? `[[${newName}${alias}]]` : `[[${newName}]]`;
        });
        await this.app.vault.modify(mmFile, updatedContent);
        const leaves = this.app.workspace.getLeavesOfType(VIEW_TYPE_MIND_MAP);
        for (const leaf of leaves) {
          const view = leaf.view;
          if (view instanceof MindMapView && view.file && view.file.path === mmFile.path) {
            if (view.render)
              view.render();
          }
        }
      }
    }
  }
  getOldFileData(oldPath) {
    const lastSlash = oldPath.lastIndexOf("/");
    const fileName = lastSlash === -1 ? oldPath : oldPath.substring(lastSlash + 1);
    const lastDot = fileName.lastIndexOf(".");
    if (lastDot === -1)
      return { basename: fileName, extension: "" };
    return {
      basename: fileName.substring(0, lastDot),
      extension: fileName.substring(lastDot + 1)
    };
  }
  escapeRegExp(string) {
    return string.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  }
  async activateView() {
    const { workspace } = this.app;
    const folder = this.settings.exportFolder || "";
    await this.ensureFolderExists(folder);
    let fileName = "Untitled.mindmap";
    let path = folder ? `${folder}/${fileName}` : fileName;
    let counter = 1;
    while (this.app.vault.getAbstractFileByPath(path)) {
      fileName = `Untitled (${counter}).mindmap`;
      path = folder ? `${folder}/${fileName}` : fileName;
      counter++;
    }
    const emptyData = {
      root: { id: "root", text: "Central idea", children: [] }
    };
    const content = `---
type: mindmap
---

\`\`\`json
${JSON.stringify(emptyData, null, 2)}
\`\`\``;
    try {
      const file = await this.app.vault.create(path, content);
      const leaf = workspace.getLeaf("tab");
      await leaf.openFile(file);
    } catch (e) {
      new import_obsidian.Notice(`Error creating mind map: ${e.message}`);
    }
  }
  async ensureFolderExists(folderPath) {
    if (!folderPath)
      return;
    const parts = folderPath.split("/");
    let currentPath = "";
    for (const part of parts) {
      currentPath = currentPath ? `${currentPath}/${part}` : part;
      const folder = this.app.vault.getAbstractFileByPath(currentPath);
      if (!folder) {
        await this.app.vault.createFolder(currentPath);
      }
    }
  }
};
var MindMapSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Export folder").setDesc("Default folder for exported files and new notes.").addText(
      (text) => text.setPlaceholder("Example: mind-maps/exports").setValue(this.plugin.settings.exportFolder).onChange((value) => {
        this.plugin.settings.exportFolder = value;
        void this.plugin.saveSettings();
      })
    ).addButton(
      (btn) => btn.setButtonText("Select folder").onClick(() => {
        new FolderSuggestModal(this.app, (folder) => {
          this.plugin.settings.exportFolder = folder.path;
          void this.plugin.saveSettings();
          this.display();
        }).open();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Theme").setDesc("Select a color theme for your mindmap nodes.").addDropdown(
      (dropdown) => dropdown.addOption("default", "Default Obsidian").addOption("vibrant", "Vibrant colors").addOption("contrast", "High contrast").setValue(this.plugin.settings.theme).onChange((value) => {
        this.plugin.settings.theme = value;
        void this.plugin.saveSettings();
        const leaves = this.app.workspace.getLeavesOfType(VIEW_TYPE_MIND_MAP);
        const view = leaves.length > 0 ? leaves[0].view : null;
        if (view instanceof MindMapView)
          view.updateTheme(this.plugin.settings.theme);
      })
    );
    new import_obsidian.Setting(containerEl).setName("Strip metadata from full note").setDesc("Automatically remove YAML frontmatter/properties when exporting content.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.stripMetadata).onChange((value) => {
        this.plugin.settings.stripMetadata = value;
        void this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Show hover preview").setDesc("Show the full node text when hovering over truncated nodes.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showHoverPreview).onChange((value) => {
        this.plugin.settings.showHoverPreview = value;
        void this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Max node text length").setDesc("The maximum number of characters to show in a node before truncating with '...'.").addSlider(
      (slider) => slider.setLimits(5, 100, 1).setValue(this.plugin.settings.maxNodeLength).setDynamicTooltip().onChange((value) => {
        this.plugin.settings.maxNodeLength = value;
        void this.plugin.saveSettings();
        const leaves = this.app.workspace.getLeavesOfType(VIEW_TYPE_MIND_MAP);
        const view = leaves.length > 0 ? leaves[0].view : null;
        if (view instanceof MindMapView)
          view.render();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Node operations").setHeading();
    const opsSection = containerEl.createDiv();
    const createOpsHotkey = (name, key) => {
      new import_obsidian.Setting(opsSection).setName(name).addText((text) => {
        text.setValue(this.plugin.settings.hotkeys[key]);
        text.inputEl.placeholder = "Press keys...";
        text.inputEl.addEventListener("keydown", (e) => {
          e.preventDefault();
          e.stopPropagation();
          if (e.key === "Escape" || e.key === "Backspace") {
            this.plugin.settings.hotkeys[key] = "";
            text.setValue("");
            void this.plugin.saveSettings();
            return;
          }
          if (["Control", "Shift", "Alt", "Meta"].includes(e.key))
            return;
          const modifiers = [];
          if (e.ctrlKey || e.metaKey)
            modifiers.push("Ctrl");
          if (e.shiftKey)
            modifiers.push("Shift");
          if (e.altKey)
            modifiers.push("Alt");
          const mainKey = e.key === " " ? "Space" : e.key;
          const fullKey = (modifiers.length > 0 ? modifiers.join("+") + "+" : "") + (mainKey.length === 1 ? mainKey.toUpperCase() : mainKey);
          this.plugin.settings.hotkeys[key] = fullKey;
          text.setValue(fullKey);
          void this.plugin.saveSettings();
        });
      });
    };
    createOpsHotkey("Add child node", "addChild");
    createOpsHotkey("Add sibling node", "addSibling");
    createOpsHotkey("Delete node", "delete");
    createOpsHotkey("Rename node", "rename");
    createOpsHotkey("Search & link note", "searchNote");
    createOpsHotkey("Create note from node", "createNote");
    createOpsHotkey("Open linked note", "openNote");
    new import_obsidian.Setting(containerEl).setName("Node style").setDesc("Choose the visual appearance of nodes.").addDropdown((dropdown) => dropdown.addOption("pill", "Pill (rounded)").addOption("rect", "Rectangle (sharp)").setValue(this.plugin.settings.nodeStyle).onChange((value) => {
      this.plugin.settings.nodeStyle = value;
      void this.plugin.saveSettings();
      this.app.workspace.getLeavesOfType(VIEW_TYPE_MIND_MAP).forEach((leaf) => {
        if (leaf.view instanceof MindMapView)
          leaf.view.render();
      });
    }));
    new import_obsidian.Setting(containerEl).setName("Navigation and movement").setHeading();
    containerEl.createEl("p", { text: "Configure how you navigate and move nodes.", cls: "setting-item-description" });
    const moveSection = containerEl.createDiv();
    new import_obsidian.Setting(moveSection).setName("Multi-node selection").setDesc("Modifier key to select multiple nodes during navigation.").addText((text) => text.setDisabled(true).setValue("Cmd / Ctrl (fixed)"));
    const createMoveHotkey = (name, key) => {
      new import_obsidian.Setting(moveSection).setName(name).addText((text) => {
        text.setValue(this.plugin.settings.hotkeys[key]);
        text.inputEl.placeholder = "Press keys...";
        text.inputEl.addEventListener("keydown", (e) => {
          e.preventDefault();
          e.stopPropagation();
          if (e.key === "Escape" || e.key === "Backspace") {
            this.plugin.settings.hotkeys[key] = "";
            text.setValue("");
            void this.plugin.saveSettings();
            return;
          }
          if (["Control", "Shift", "Alt", "Meta"].includes(e.key))
            return;
          const modifiers = [];
          if (e.ctrlKey || e.metaKey)
            modifiers.push("Ctrl");
          if (e.shiftKey)
            modifiers.push("Shift");
          if (e.altKey)
            modifiers.push("Alt");
          const mainKey = e.key === " " ? "Space" : e.key;
          const fullKey = (modifiers.length > 0 ? modifiers.join("+") + "+" : "") + (mainKey.length === 1 ? mainKey.toUpperCase() : mainKey);
          this.plugin.settings.hotkeys[key] = fullKey;
          text.setValue(fullKey);
          void this.plugin.saveSettings();
        });
      });
    };
    createMoveHotkey("Move node up (Shift+)", "reorderUp");
    createMoveHotkey("Move node down (Shift+)", "reorderDown");
    createMoveHotkey("Demote node (Shift+move right)", "demote");
    createMoveHotkey("Fold/unfold subtree", "toggleCollapse");
    new import_obsidian.Setting(containerEl).setName("Support").setHeading();
    const supportDiv = containerEl.createDiv();
    supportDiv.createEl("p", { text: "If you find this plugin helpful, please consider supporting the development!" });
    const coffeeBtn = supportDiv.createEl("a", { href: "https://www.buymeacoffee.com/creative781", cls: "obsimap-support-coffee" });
    coffeeBtn.createEl("img", {
      attr: {
        src: "https://cdn.buymeacoffee.com/buttons/v2/default-yellow.png",
        alt: "Buy Me A Coffee"
      }
    });
    const socialDiv = supportDiv.createDiv({ cls: "obsimap-social-links" });
    socialDiv.createEl("a", {
      href: "https://www.youtube.com/@creative781",
      text: "\u{1F4FA} YouTube channel",
      cls: "obsimap-social-link"
    });
    socialDiv.createEl("a", {
      href: "https://creative781.cafe24.com/",
      text: "\u{1F3E0} official blog",
      cls: "obsimap-social-link"
    });
  }
};
var FolderSuggestModal = class extends import_obsidian.FuzzySuggestModal {
  constructor(app, onSelect) {
    super(app);
    this.onSelect = onSelect;
    this.folders = this.app.vault.getAllLoadedFiles().filter((f) => f instanceof import_obsidian.TFolder);
  }
  getItems() {
    return this.folders;
  }
  getItemText(item) {
    return item.path;
  }
  onChooseItem(item, evt) {
    this.onSelect(item);
  }
};
var SaveModal = class extends import_obsidian.Modal {
  constructor(app, defaultName, onSave) {
    super(app);
    this.fileName = defaultName;
    this.onSave = onSave;
  }
  onOpen() {
    const { contentEl } = this;
    new import_obsidian.Setting(contentEl).setName("Save mind map").setHeading();
    new import_obsidian.Setting(contentEl).setName("File name").addText(
      (text) => text.setValue(this.fileName).onChange((value) => this.fileName = value)
    );
    new import_obsidian.Setting(contentEl).addButton(
      (btn) => btn.setButtonText("Save").setCta().onClick(() => {
        void this.onSave(this.fileName);
        this.close();
      })
    );
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var _MindMapView = class extends import_obsidian.TextFileView {
  constructor(leaf, plugin) {
    super(leaf);
    this.selectedNodeId = null;
    this.selectedNodeIds = /* @__PURE__ */ new Set();
    this.zoom = 1;
    this.panX = 0;
    this.panY = 0;
    this.isDragging = false;
    this.lastMouseX = 0;
    this.lastMouseY = 0;
    this.isEditing = false;
    /** Rename chosen from context menu; started after menu closes so focus is not stolen. */
    this.pendingContextMenuRename = null;
    this.historyStack = [];
    // Internal Drag and Drop state
    this.draggedNodeId = null;
    this.dragTargetNodeId = null;
    this.dragDropMode = null;
    this.ghostNode = null;
    this.dragStartX = 0;
    this.dragStartY = 0;
    this.isInternalDragging = false;
    this.isToolbarExpanded = false;
    this.currentTooltip = null;
    this.suppressNextClick = false;
    this.suppressHotkeysUntil = 0;
    this.editInputEl = null;
    this.editViewportResizeHandler = null;
    this.viewportResizeObserver = null;
    this.viewportResizeRaf = null;
    this.svgContainerEl = null;
    this.boundWindowKeyDown = null;
    this.plugin = plugin;
    this.settings = plugin.settings;
    this.metadataCache = plugin.app.metadataCache;
    this.mindMapData = {
      root: {
        id: "root",
        text: "Central idea",
        children: []
      }
    };
    this.selectedNodeId = "root";
    this.selectedNodeIds.add("root");
  }
  focusContainer() {
    const container = this.containerEl.querySelector(".mindmap-svg-container");
    if (container instanceof HTMLElement) {
      container.focus({ preventScroll: true });
    }
  }
  isNodeTextEditActive() {
    return this.editInputEl !== null && document.activeElement === this.editInputEl;
  }
  endNodeTextEdit() {
    if (this.editInputEl) {
      this.editInputEl.blur();
    }
    this.teardownEditInput();
  }
  getViewType() {
    return VIEW_TYPE_MIND_MAP;
  }
  getIcon() {
    return "lucide-git-graph";
  }
  getDisplayText() {
    if (this.file)
      return this.file.basename;
    return "Simple Mindmap";
  }
  getViewData() {
    const jsonData = JSON.stringify(this.mindMapData, null, 2);
    return `---
type: mindmap
---

\`\`\`json
${jsonData}
\`\`\``;
  }
  setViewData(data, clear) {
    const jsonMatch = data.match(/```json\n([\s\S]*?)\n```/);
    if (jsonMatch) {
      try {
        this.mindMapData = JSON.parse(jsonMatch[1]);
        if (this.mindMapData.root) {
          this.selectedNodeId = this.mindMapData.root.id;
          this.selectedNodeIds.clear();
          this.selectedNodeIds.add(this.mindMapData.root.id);
        }
      } catch (e) {
        console.error("Failed to parse mindmap data:", e);
      }
    }
    this.render();
    setTimeout(() => this.focusContainer(), 200);
  }
  clear() {
    this.mindMapData = {
      root: { id: "root", text: "Central idea", children: [] }
    };
    this.selectedNodeId = "root";
    this.selectedNodeIds.clear();
    this.selectedNodeIds.add("root");
    this.render();
  }
  async onOpen() {
    await super.onOpen();
    const container = this.contentEl;
    container.empty();
    container.classList.add("mind-map-view");
    container.classList.add(`theme-${this.settings.theme}`);
    const svgContainer = container.createEl("div", { cls: "mindmap-svg-container" });
    this.svgContainerEl = svgContainer;
    svgContainer.tabIndex = 0;
    const controls = svgContainer.createEl("div", { cls: "mindmap-controls-floating" });
    if (!this.isToolbarExpanded)
      controls.classList.add("is-collapsed");
    const toggleBtn = this.createControlButton(controls, "lucide-menu", "Menu", () => {
      this.isToolbarExpanded = !this.isToolbarExpanded;
      controls.classList.toggle("is-collapsed", !this.isToolbarExpanded);
      const iconEl = toggleBtn.querySelector(".lucide");
      if (iconEl instanceof Element)
        iconEl.replaceWith(document.createElement("div"));
      (0, import_obsidian.setIcon)(toggleBtn, this.isToolbarExpanded ? "lucide-chevron-left" : "lucide-menu");
    });
    toggleBtn.classList.add("toolbar-toggle-btn");
    (0, import_obsidian.setIcon)(toggleBtn, this.isToolbarExpanded ? "lucide-chevron-left" : "lucide-menu");
    const btnContainer = controls.createEl("div", { cls: "toolbar-buttons" });
    this.createControlButton(btnContainer, "lucide-file-input", "Import markdown", () => void this.promptImport());
    this.createControlButton(btnContainer, "lucide-file-output", "Export markdown", () => void this.exportMarkdown());
    this.createControlButton(btnContainer, "lucide-file-text", "Full note", () => void this.exportFullNote());
    this.svg = document.createElementNS("http://www.w3.org/2000/svg", "svg");
    this.svg.setAttribute("width", "100%");
    this.svg.setAttribute("height", "100%");
    this.svg.classList.add("mindmap-svg");
    svgContainer.appendChild(this.svg);
    setTimeout(() => {
      svgContainer.focus();
    }, 100);
    this.g = document.createElementNS("http://www.w3.org/2000/svg", "g");
    this.svg.appendChild(this.g);
    this.textMeasureEl = document.createElementNS("http://www.w3.org/2000/svg", "text");
    this.textMeasureEl.classList.add("mindmap-node-text");
    this.textMeasureEl.setAttribute("visibility", "hidden");
    this.textMeasureEl.setAttribute("aria-hidden", "true");
    this.svg.appendChild(this.textMeasureEl);
    this.boundWindowKeyDown = (e) => {
      if (this.app.workspace.getActiveViewOfType(_MindMapView) !== this)
        return;
      if (Date.now() < this.suppressHotkeysUntil)
        return;
      if (this.isNodeTextEditActive())
        return;
      const targetEl = e.target instanceof HTMLElement ? e.target : null;
      if (targetEl && targetEl.classList.contains("mindmap-edit-input"))
        return;
      if (targetEl && targetEl.closest(".view-header"))
        return;
      if (targetEl && (targetEl.tagName === "INPUT" || targetEl.tagName === "TEXTAREA" || targetEl.isContentEditable))
        return;
      if (targetEl && targetEl.closest(".mindmap-control-btn"))
        return;
      if (targetEl && targetEl.closest(".menu"))
        return;
      if (e.key === " ") {
        svgContainer.setCssProps({ "cursor": "grab" });
      }
      if (e.key === "F2") {
        e.preventDefault();
        this.renameFile();
        return;
      }
      this.handleKeyDown(e);
    };
    window.addEventListener("keydown", this.boundWindowKeyDown, false);
    this.registerDomEvent(svgContainer, "dragover", (e) => {
      e.preventDefault();
      if (e.dataTransfer)
        e.dataTransfer.dropEffect = "copy";
      const target = this.findDropTargetAt(e.clientX, e.clientY);
      if (target) {
        if (this.dragTargetNodeId !== target.node.id || this.dragDropMode !== target.mode) {
          this.dragTargetNodeId = target.node.id;
          this.dragDropMode = target.mode;
          this.updateVisualIndicators();
        }
      } else if (this.dragTargetNodeId) {
        this.dragTargetNodeId = null;
        this.dragDropMode = null;
        this.updateVisualIndicators();
      }
    });
    this.registerDomEvent(svgContainer, "drop", (e) => {
      e.preventDefault();
      const target = this.findDropTargetAt(e.clientX, e.clientY);
      this.dragTargetNodeId = null;
      this.dragDropMode = null;
      this.updateVisualIndicators();
      if (!target)
        return;
      this.handleExternalDrop(e, target.node, target.mode);
    });
    this.registerDomEvent(svgContainer, "keyup", (e) => {
      if (e.key === " ") {
        if (!this.isDragging)
          svgContainer.setCssProps({ "cursor": "default" });
      }
    });
    this.registerDomEvent(this.svg, "wheel", (e) => {
      e.preventDefault();
      const zoomSpeed = 1e-3;
      this.zoom -= e.deltaY * zoomSpeed;
      this.zoom = Math.max(0.1, Math.min(this.zoom, 5));
      this.updateTransform();
    });
    this.registerDomEvent(this.svg, "pointerdown", (e) => {
      if (e.button === 0 || e.button === 1) {
        this.focusContainer();
        this.isDragging = true;
        this.lastMouseX = e.clientX;
        this.lastMouseY = e.clientY;
        svgContainer.setCssProps({ "cursor": "grabbing" });
        this.svg.setPointerCapture(e.pointerId);
      }
    });
    this.registerDomEvent(this.svg, "pointermove", (e) => {
      if (this.isDragging) {
        const dx = e.clientX - this.lastMouseX;
        const dy = e.clientY - this.lastMouseY;
        this.panX += dx;
        this.panY += dy;
        this.lastMouseX = e.clientX;
        this.lastMouseY = e.clientY;
        this.updateTransform();
      }
    });
    this.registerDomEvent(this.svg, "pointerup", (e) => {
      this.isDragging = false;
      if (this.svg) {
        const svgContainer2 = this.containerEl.querySelector(".mindmap-svg-container");
        if (svgContainer2 instanceof HTMLElement)
          svgContainer2.setCssProps({ "cursor": "default" });
        this.svg.releasePointerCapture(e.pointerId);
      }
    });
    this.registerEvent(this.app.workspace.on("active-leaf-change", (leaf) => {
      if (leaf === this.leaf) {
        setTimeout(() => this.focusContainer(), 50);
      }
    }));
    this.viewportResizeObserver = new ResizeObserver(() => {
      if (this.viewportResizeRaf !== null)
        cancelAnimationFrame(this.viewportResizeRaf);
      this.viewportResizeRaf = requestAnimationFrame(() => {
        this.viewportResizeRaf = null;
        if (this.selectedNodeId)
          this.scrollSelectionIntoView();
      });
    });
    this.viewportResizeObserver.observe(svgContainer);
    this.register(() => {
      var _a;
      if (this.viewportResizeRaf !== null)
        cancelAnimationFrame(this.viewportResizeRaf);
      (_a = this.viewportResizeObserver) == null ? void 0 : _a.disconnect();
      this.viewportResizeObserver = null;
    });
    this.render();
  }
  createControlButton(container, iconId, tooltip, onClick) {
    const btn = container.createEl("div", { cls: "mindmap-control-btn" });
    (0, import_obsidian.setIcon)(btn, iconId);
    (0, import_obsidian.setTooltip)(btn, tooltip);
    this.registerDomEvent(btn, "click", () => {
      onClick();
      requestAnimationFrame(() => this.focusContainer());
    });
    return btn;
  }
  updateTransform() {
    this.g.setAttribute("transform", `translate(${this.panX}, ${this.panY}) scale(${this.zoom})`);
    this.repositionActiveEditInput();
  }
  repositionActiveEditInput() {
    if (!this.editInputEl || !this.selectedNodeId)
      return;
    const node = this.findNodeById(this.mindMapData.root, this.selectedNodeId);
    if (node)
      this.positionEditInput(this.editInputEl, node);
  }
  scrollSelectionIntoView() {
    if (this.selectedNodeId)
      this.ensureNodeInView(this.selectedNodeId);
  }
  /** Pan just enough so the node fits in the visible map pane (uses live DOM bounds). */
  ensureNodeInView(nodeId) {
    var _a, _b, _c;
    if (!this.svgContainerEl || !this.g)
      return;
    const padding = 24;
    const containerRect = this.svgContainerEl.getBoundingClientRect();
    const viewLeft = padding;
    const viewTop = padding;
    const viewRight = containerRect.width - padding;
    const viewBottom = containerRect.height - padding;
    const viewInnerW = viewRight - viewLeft;
    const viewInnerH = viewBottom - viewTop;
    let left;
    let top;
    let right;
    let bottom;
    const nodeEl = (_a = this.svg) == null ? void 0 : _a.querySelector(`[data-node-id="${nodeId}"]`);
    if (nodeEl instanceof SVGGElement) {
      const nodeRect = nodeEl.getBoundingClientRect();
      left = nodeRect.left - containerRect.left;
      top = nodeRect.top - containerRect.top;
      right = nodeRect.right - containerRect.left;
      bottom = nodeRect.bottom - containerRect.top;
    } else {
      const node = this.findNodeById(this.mindMapData.root, nodeId);
      if (!node)
        return;
      const nodeWidth = this.getNodeWidth(node.text);
      const extraRight = node.children.length > 0 ? 26 : 0;
      left = this.panX + ((_b = node.x) != null ? _b : 0) * this.zoom;
      top = this.panY + ((_c = node.y) != null ? _c : 0) * this.zoom;
      right = left + (nodeWidth + extraRight) * this.zoom;
      bottom = top + _MindMapView.NODE_HEIGHT * this.zoom;
    }
    let dx = 0;
    let dy = 0;
    const nodeW = right - left;
    const nodeH = bottom - top;
    if (nodeW <= viewInnerW) {
      if (left < viewLeft)
        dx = viewLeft - left;
      else if (right > viewRight)
        dx = viewRight - right;
    } else {
      dx = viewLeft - left;
    }
    if (nodeH <= viewInnerH) {
      if (top < viewTop)
        dy = viewTop - top;
      else if (bottom > viewBottom)
        dy = viewBottom - bottom;
    } else {
      dy = viewTop - top;
    }
    if (dx === 0 && dy === 0)
      return;
    this.panX += dx;
    this.panY += dy;
    this.g.setAttribute("transform", `translate(${this.panX}, ${this.panY}) scale(${this.zoom})`);
    this.repositionActiveEditInput();
  }
  handleKeyDown(e) {
    var _a, _b;
    if (this.isNodeTextEditActive()) {
      return;
    }
    if (this.editInputEl && document.activeElement !== this.editInputEl) {
      this.teardownEditInput();
    } else if (this.isEditing && !this.editInputEl) {
      this.isEditing = false;
    }
    if (((_a = document.activeElement) == null ? void 0 : _a.tagName) === "INPUT" || ((_b = document.activeElement) == null ? void 0 : _b.tagName) === "TEXTAREA") {
      return;
    }
    if (!this.selectedNodeId)
      return;
    const nodeId = this.selectedNodeId;
    const hotkeys = this.settings.hotkeys;
    const modifiers = [];
    if (e.ctrlKey || e.metaKey)
      modifiers.push("Ctrl");
    if (e.shiftKey)
      modifiers.push("Shift");
    if (e.altKey)
      modifiers.push("Alt");
    const key = e.key;
    const fullKey = (modifiers.length > 0 ? modifiers.join("+") + "+" : "") + key;
    if ((e.ctrlKey || e.metaKey) && e.key.toLowerCase() === "z") {
      e.preventDefault();
      this.undo();
      return;
    }
    const matches = (configKey) => {
      if (!configKey)
        return false;
      const normalizedKey = key === " " ? "Space" : key;
      if (configKey === fullKey)
        return true;
      if (configKey === normalizedKey && modifiers.length === 0)
        return true;
      const parts = configKey.split("+");
      const configModifiers = parts.slice(0, -1);
      const configMainKey = parts[parts.length - 1];
      if (configMainKey.toLowerCase() !== normalizedKey.toLowerCase())
        return false;
      if (configModifiers.length !== modifiers.length)
        return false;
      return configModifiers.every((m) => modifiers.includes(m));
    };
    const isMultiSelect = e.ctrlKey || e.metaKey;
    const isShift = e.shiftKey;
    if (isShift) {
      if (key === "ArrowUp") {
        e.preventDefault();
        this.reorderNode(-1);
        return;
      }
      if (key === "ArrowDown") {
        e.preventDefault();
        this.reorderNode(1);
        return;
      }
      if (key === "ArrowLeft") {
        e.preventDefault();
        this.promoteNode();
        return;
      }
      if (key === "ArrowRight") {
        e.preventDefault();
        this.demoteNode();
        return;
      }
    }
    if (key === "ArrowUp" || key === "ArrowDown" || key === "ArrowLeft" || key === "ArrowRight") {
      e.preventDefault();
      if (key === "ArrowUp")
        this.navigateSibling(-1, isMultiSelect);
      else if (key === "ArrowDown")
        this.navigateSibling(1, isMultiSelect);
      else if (key === "ArrowLeft")
        this.navigateParent(isMultiSelect);
      else if (key === "ArrowRight")
        this.navigateChild(isMultiSelect);
      return;
    }
    if (matches(hotkeys.addChild)) {
      e.preventDefault();
      this.addChildNode(nodeId);
    } else if (matches(hotkeys.addSibling)) {
      e.preventDefault();
      this.addSiblingNode(nodeId);
    } else if (matches(hotkeys.delete) || key === "Backspace" && hotkeys.delete === "Delete") {
      e.preventDefault();
      this.deleteNode(nodeId);
    } else if (matches(hotkeys.rename)) {
      e.preventDefault();
      const node = this.findNodeById(this.mindMapData.root, nodeId);
      if (node)
        this.editNode(node);
    } else if (matches(hotkeys.reorderUp)) {
      e.preventDefault();
      this.reorderNode(-1);
    } else if (matches(hotkeys.reorderDown)) {
      e.preventDefault();
      this.reorderNode(1);
    } else if (matches(hotkeys.promote)) {
      e.preventDefault();
      this.promoteNode();
    } else if (matches(hotkeys.demote)) {
      e.preventDefault();
      this.demoteNode();
    } else if (matches(hotkeys.searchNote)) {
      e.preventDefault();
      this.openNoteSearch();
    } else if (matches(hotkeys.createNote)) {
      e.preventDefault();
      void this.createNoteFromNode();
    } else if (matches(hotkeys.openNote)) {
      e.preventDefault();
      void this.openLinkedNote();
    } else if (matches(hotkeys.toggleCollapse)) {
      e.preventDefault();
      this.toggleCollapse();
    }
  }
  toggleCollapse() {
    if (this.selectedNodeIds.size === 0)
      return;
    this.pushHistory();
    let changed = false;
    this.selectedNodeIds.forEach((id) => {
      const node = this.findNodeById(this.mindMapData.root, id);
      if (node && node.children.length > 0) {
        node.collapsed = !node.collapsed;
        changed = true;
      }
    });
    if (changed) {
      this.render();
      void this.saveMindMap(true);
    }
  }
  getNodeDepth(nodeId) {
    if (nodeId === "root")
      return 0;
    let depth = 0;
    let currentId = nodeId;
    while (currentId !== "root") {
      const parent = this.findParentNode(this.mindMapData.root, currentId);
      if (!parent)
        return -1;
      currentId = parent.id;
      depth++;
    }
    return depth;
  }
  /** True when the node is rendered (every ancestor expanded). */
  isNodeDisplayed(nodeId) {
    if (nodeId === "root")
      return true;
    const parent = this.findParentNode(this.mindMapData.root, nodeId);
    if (!parent)
      return false;
    if (parent.collapsed)
      return false;
    return this.isNodeDisplayed(parent.id);
  }
  /** All visible nodes at a given tree depth, in on-screen top-to-bottom order. */
  getNodesAtDepth(depth) {
    const nodes = [];
    const walk = (node, currentDepth) => {
      if (currentDepth === depth) {
        if (node.id !== "root" && this.isNodeDisplayed(node.id)) {
          nodes.push(node);
        }
        return;
      }
      if (node.collapsed)
        return;
      for (const child of node.children) {
        walk(child, currentDepth + 1);
      }
    };
    walk(this.mindMapData.root, 0);
    return nodes.sort((a, b) => {
      var _a, _b, _c, _d;
      const ay = (_a = a.y) != null ? _a : 0;
      const by = (_b = b.y) != null ? _b : 0;
      if (ay !== by)
        return ay - by;
      return ((_c = a.x) != null ? _c : 0) - ((_d = b.x) != null ? _d : 0);
    });
  }
  navigateSibling(direction, isMultiSelect = false) {
    if (!this.selectedNodeId)
      return;
    if (this.selectedNodeId === "root") {
      const children = this.mindMapData.root.children;
      if (children.length === 0)
        return;
      const target = direction > 0 ? children[0] : children[children.length - 1];
      this.selectedNodeId = target.id;
      if (!isMultiSelect) {
        this.selectedNodeIds.clear();
      }
      this.selectedNodeIds.add(this.selectedNodeId);
      this.render();
      this.ensureNodeInView(this.selectedNodeId);
      return;
    }
    this.calculateLayout(this.mindMapData.root, 100, 300);
    const depth = this.getNodeDepth(this.selectedNodeId);
    if (depth < 0)
      return;
    const peers = this.getNodesAtDepth(depth);
    const index = peers.findIndex((n) => n.id === this.selectedNodeId);
    if (index < 0)
      return;
    const nextIndex = index + direction;
    if (nextIndex < 0 || nextIndex >= peers.length)
      return;
    this.selectedNodeId = peers[nextIndex].id;
    if (!isMultiSelect) {
      this.selectedNodeIds.clear();
    }
    this.selectedNodeIds.add(this.selectedNodeId);
    this.render();
    this.ensureNodeInView(this.selectedNodeId);
  }
  navigateParent(isMultiSelect = false) {
    if (!this.selectedNodeId || this.selectedNodeId === "root")
      return;
    const parent = this.findParentNode(this.mindMapData.root, this.selectedNodeId);
    if (parent) {
      this.selectedNodeId = parent.id;
      if (!isMultiSelect) {
        this.selectedNodeIds.clear();
      }
      this.selectedNodeIds.add(this.selectedNodeId);
      this.render();
      this.ensureNodeInView(this.selectedNodeId);
    }
  }
  navigateChild(isMultiSelect = false) {
    if (!this.selectedNodeId)
      return;
    const node = this.findNodeById(this.mindMapData.root, this.selectedNodeId);
    if (node && node.children.length > 0) {
      this.selectedNodeId = node.children[0].id;
      if (!isMultiSelect) {
        this.selectedNodeIds.clear();
      }
      this.selectedNodeIds.add(this.selectedNodeId);
      this.render();
      this.ensureNodeInView(this.selectedNodeId);
    }
  }
  reorderNode(direction) {
    if (this.selectedNodeIds.size === 0 || this.selectedNodeIds.has("root"))
      return;
    const firstId = this.selectedNodeIds.values().next().value;
    const parent = this.findParentNode(this.mindMapData.root, firstId);
    if (parent) {
      this.pushHistory();
      const sortedIds = Array.from(this.selectedNodeIds).sort((a, b) => {
        return parent.children.findIndex((n) => n.id === a) - parent.children.findIndex((n) => n.id === b);
      });
      if (direction === -1) {
        for (const id of sortedIds) {
          const index = parent.children.findIndex((n) => n.id === id);
          if (index > 0) {
            const targetIndex = index - 1;
            if (!this.selectedNodeIds.has(parent.children[targetIndex].id)) {
              const [moved] = parent.children.splice(index, 1);
              parent.children.splice(targetIndex, 0, moved);
            }
          }
        }
      } else {
        for (const id of sortedIds.reverse()) {
          const index = parent.children.findIndex((n) => n.id === id);
          if (index < parent.children.length - 1) {
            const targetIndex = index + 1;
            if (!this.selectedNodeIds.has(parent.children[targetIndex].id)) {
              const [moved] = parent.children.splice(index, 1);
              parent.children.splice(targetIndex, 0, moved);
            }
          }
        }
      }
      this.render();
      this.scrollSelectionIntoView();
      void this.saveMindMap(true);
    }
  }
  promoteNode() {
    if (this.selectedNodeIds.size === 0 || this.selectedNodeIds.has("root"))
      return;
    const firstId = this.selectedNodeIds.values().next().value;
    const parent = this.findParentNode(this.mindMapData.root, firstId);
    if (!parent || parent.id === "root")
      return;
    const grandParent = this.findParentNode(this.mindMapData.root, parent.id);
    if (grandParent) {
      this.pushHistory();
      const sortedIds = Array.from(this.selectedNodeIds).sort((a, b) => {
        return parent.children.findIndex((n) => n.id === a) - parent.children.findIndex((n) => n.id === b);
      });
      const parentIndexInGrandParent = grandParent.children.findIndex((n) => n.id === parent.id);
      let insertOffset = 1;
      for (const id of sortedIds) {
        const indexInParent = parent.children.findIndex((n) => n.id === id);
        const [moved] = parent.children.splice(indexInParent, 1);
        moved.parent = grandParent.id;
        grandParent.children.splice(parentIndexInGrandParent + insertOffset, 0, moved);
        insertOffset++;
      }
      this.render();
      this.scrollSelectionIntoView();
      void this.saveMindMap(true);
    }
  }
  demoteNode() {
    if (this.selectedNodeIds.size === 0 || this.selectedNodeIds.has("root"))
      return;
    const firstId = this.selectedNodeIds.values().next().value;
    const parent = this.findParentNode(this.mindMapData.root, firstId);
    if (parent) {
      this.pushHistory();
      const sortedIds = Array.from(this.selectedNodeIds).sort((a, b) => {
        return parent.children.findIndex((n) => n.id === a) - parent.children.findIndex((n) => n.id === b);
      });
      const firstIndex = parent.children.findIndex((n) => n.id === sortedIds[0]);
      if (firstIndex > 0) {
        const previousSibling = parent.children[firstIndex - 1];
        for (const id of sortedIds) {
          const index = parent.children.findIndex((n) => n.id === id);
          const [moved] = parent.children.splice(index, 1);
          moved.parent = previousSibling.id;
          previousSibling.children.push(moved);
        }
        this.render();
        this.scrollSelectionIntoView();
        void this.saveMindMap(true);
      }
    }
  }
  promptImport() {
    new FileSuggestModal(this.app, (file) => {
      void this.importMarkdown(file);
    }).open();
  }
  async importMarkdown(file) {
    const targetFile = file || this.app.workspace.getActiveFile();
    if (!targetFile)
      return;
    let content = await this.app.vault.read(targetFile);
    content = content.replace(/^---[\s\S]*?---\n?/, "");
    const lines = content.split("\n");
    const rootNode = {
      id: "root",
      text: targetFile.basename,
      children: []
    };
    const stack = [
      { node: rootNode, level: -1 }
    ];
    let lastHeadingLevel = 0;
    lines.forEach((line, index) => {
      if (!line.trim())
        return;
      let level = -1;
      let text = "";
      const headingMatch = line.match(/^(#+)\s+(.*)/);
      if (headingMatch) {
        level = headingMatch[1].length;
        text = headingMatch[2].trim();
        lastHeadingLevel = level;
      } else {
        const listMatch = line.match(/^(\s*)(?:-|\*|\d+\.)\s+(.*)/);
        if (listMatch) {
          const indentStr = listMatch[1].replace(/\t/g, "  ");
          level = lastHeadingLevel + indentStr.length + 1;
          text = listMatch[2].trim();
        }
      }
      if (level !== -1) {
        const node = {
          id: `${Date.now()}-${index}-${Math.random().toString(36).substring(2, 7)}`,
          text,
          children: []
        };
        while (stack.length > 1 && stack[stack.length - 1].level >= level) {
          stack.pop();
        }
        const parent = stack[stack.length - 1].node;
        node.parent = parent.id;
        parent.children.push(node);
        stack.push({ node, level });
      }
    });
    this.mindMapData.root = rootNode;
    this.selectedNodeId = rootNode.id;
    this.selectedNodeIds.clear();
    this.selectedNodeIds.add(rootNode.id);
    this.render();
    void this.saveMindMap(true);
  }
  async ensureFolderExists(folderPath) {
    if (!folderPath)
      return;
    const parts = folderPath.split("/");
    let currentPath = "";
    for (const part of parts) {
      currentPath = currentPath ? `${currentPath}/${part}` : part;
      const folder = this.app.vault.getAbstractFileByPath(currentPath);
      if (!folder) {
        await this.app.vault.createFolder(currentPath);
      }
    }
  }
  async exportFullNote() {
    const rootNode = this.mindMapData.root;
    const baseFileName = `${rootNode.text.replace(/[/\\?%*:|"<>]/g, "-").trim() || "Untitled"} (Full Note)`;
    const folder = this.settings.exportFolder;
    await this.ensureFolderExists(folder);
    let fileName = `${baseFileName}.md`;
    let path = folder ? `${folder}/${fileName}` : fileName;
    let counter = 1;
    while (await this.app.vault.adapter.exists(path)) {
      fileName = `${baseFileName} (${counter}).md`;
      path = folder ? `${folder}/${fileName}` : fileName;
      counter++;
    }
    const markdown = await this.nodeToFullMarkdown(rootNode, 1);
    try {
      await this.app.vault.create(path, markdown);
      new import_obsidian.Notice(`Full mind map exported: ${path}`);
      const newFile = this.app.vault.getAbstractFileByPath(path);
      if (newFile instanceof import_obsidian.TFile) {
        await this.app.workspace.getLeaf("tab").openFile(newFile);
      }
    } catch (e) {
      new import_obsidian.Notice(`Failed to export full note: ${e.message}`);
    }
  }
  async nodeToFullMarkdown(node, level) {
    const indent = "    ".repeat(level - 1);
    let md = `${indent}- **${node.text}**
`;
    const wikiLinkMatch = node.text.match(/\[\[([^\]|]+)(?:\|[^\]]+)?\]\]/);
    if (wikiLinkMatch) {
      const fileName = wikiLinkMatch[1];
      const file = this.app.metadataCache.getFirstLinkpathDest(fileName, "");
      if (file instanceof import_obsidian.TFile) {
        let content = await this.app.vault.read(file);
        if (this.settings.stripMetadata) {
          content = content.replace(/^---\n([\s\S]*?)\n---\n/, "");
        }
        const contentLines = content.split("\n").map((line) => {
          const trimmedLine = line.trim();
          if (trimmedLine.startsWith("#")) {
            const cleanHeader = trimmedLine.replace(/^#+\s*/, "");
            return `${indent}    **\u25C8 ${cleanHeader}**`;
          }
          return `${indent}    ${line}`;
        }).join("\n");
        md += `${contentLines}
`;
      }
    }
    for (const child of node.children) {
      md += await this.nodeToFullMarkdown(child, level + 1);
    }
    return md;
  }
  async exportMarkdown() {
    const rootNode = this.mindMapData.root;
    const baseFileName = (rootNode.text.replace(/[/\\?%*:|"<>]/g, "-").trim() || "Untitled Simple Mindmap") + " (Outline)";
    const folder = this.settings.exportFolder;
    await this.ensureFolderExists(folder);
    let fileName = `${baseFileName}.md`;
    let path = folder ? `${folder}/${fileName}` : fileName;
    let counter = 1;
    while (await this.app.vault.adapter.exists(path)) {
      fileName = `${baseFileName} (${counter}).md`;
      path = folder ? `${folder}/${fileName}` : fileName;
      counter++;
    }
    let markdown = "";
    rootNode.children.forEach((child) => {
      markdown += this.nodeToMarkdown(child, 1);
    });
    try {
      await this.app.vault.create(path, markdown);
      new import_obsidian.Notice(`Mind map exported as a new file: ${path}`);
      const newFile = this.app.vault.getAbstractFileByPath(path);
      if (newFile instanceof import_obsidian.TFile) {
        await this.app.workspace.getLeaf("tab").openFile(newFile);
      }
    } catch (e) {
      new import_obsidian.Notice(`Failed to export: ${e.message}`);
      console.error(e);
    }
  }
  nodeToMarkdown(node, level) {
    const indent = "    ".repeat(level - 1);
    let md = `${indent}- ${node.text}
`;
    node.children.forEach((child) => {
      md += this.nodeToMarkdown(child, level + 1);
    });
    return md;
  }
  addChildNode(parentId, text) {
    const isInitial = text === void 0;
    const actualText = isInitial ? "" : text;
    const parent = this.findNodeById(this.mindMapData.root, parentId);
    if (parent) {
      parent.collapsed = false;
      this.pushHistory();
      const newNode = {
        id: Date.now().toString(),
        text: actualText,
        children: [],
        parent: parentId
      };
      parent.children.push(newNode);
      this.selectedNodeId = newNode.id;
      this.selectedNodeIds.clear();
      this.selectedNodeIds.add(this.selectedNodeId);
      this.render();
      this.scrollSelectionIntoView();
      if (isInitial) {
        this.editNode(newNode, "New child");
      } else {
        void this.saveMindMap(true);
      }
    }
  }
  addSiblingNode(nodeId, text) {
    if (nodeId === "root")
      return;
    const isInitial = text === void 0;
    const actualText = isInitial ? "" : text;
    const parent = this.findParentNode(this.mindMapData.root, nodeId);
    if (parent) {
      this.pushHistory();
      const newNode = {
        id: Date.now().toString(),
        text: actualText,
        children: [],
        parent: parent.id
      };
      const index = parent.children.findIndex((n) => n.id === nodeId);
      parent.children.splice(index + 1, 0, newNode);
      this.selectedNodeId = newNode.id;
      this.selectedNodeIds.clear();
      this.selectedNodeIds.add(this.selectedNodeId);
      this.render();
      this.scrollSelectionIntoView();
      if (isInitial) {
        this.editNode(newNode, "New sibling");
      } else {
        void this.saveMindMap(true);
      }
    }
  }
  deleteNode(nodeId) {
    if (nodeId === "root" || this.selectedNodeIds.has("root"))
      return;
    const idsToDelete = this.selectedNodeIds.has(nodeId) ? Array.from(this.selectedNodeIds) : [nodeId];
    let parent = null;
    this.pushHistory();
    for (const id of idsToDelete) {
      const p = this.findParentNode(this.mindMapData.root, id);
      if (p) {
        parent = p;
        p.children = p.children.filter((n) => n.id !== id);
      }
    }
    if (parent) {
      this.selectedNodeId = parent.id;
      this.selectedNodeIds.clear();
      this.selectedNodeIds.add(parent.id);
    } else {
      this.selectedNodeId = "root";
      this.selectedNodeIds.clear();
      this.selectedNodeIds.add("root");
    }
    this.render();
    void this.saveMindMap(true);
  }
  findNodeById(node, id) {
    if (node.id === id)
      return node;
    for (const child of node.children) {
      const found = this.findNodeById(child, id);
      if (found)
        return found;
    }
    return null;
  }
  findParentNode(node, childId) {
    for (const child of node.children) {
      if (child.id === childId)
        return node;
      const parent = this.findParentNode(child, childId);
      if (parent)
        return parent;
    }
    return null;
  }
  selectNode(nodeId, isMultiSelect, shouldRender = true) {
    if (isMultiSelect) {
      const currentParent = this.findParentNode(this.mindMapData.root, nodeId);
      if (this.selectedNodeIds.size > 0) {
        const firstId = this.selectedNodeIds.values().next().value;
        const firstParent = this.findParentNode(this.mindMapData.root, firstId);
        if ((firstParent == null ? void 0 : firstParent.id) === (currentParent == null ? void 0 : currentParent.id)) {
          if (this.selectedNodeIds.has(nodeId)) {
            this.selectedNodeIds.delete(nodeId);
          } else {
            this.selectedNodeIds.add(nodeId);
          }
        } else {
          this.selectedNodeIds.clear();
          this.selectedNodeIds.add(nodeId);
        }
      } else {
        this.selectedNodeIds.add(nodeId);
      }
    } else {
      this.selectedNodeId = nodeId;
      this.selectedNodeIds.clear();
      this.selectedNodeIds.add(nodeId);
    }
    if (shouldRender)
      this.render();
  }
  openNodeContextMenu(node, x, y) {
    this.selectNode(node.id, false);
    const menu = new import_obsidian.Menu();
    if (node.id !== "root") {
      menu.addItem((item) => {
        item.setTitle("Add sibling").setIcon("plus-with-circle").onClick(() => {
          this.addSiblingNode(node.id);
        });
      });
    }
    menu.addItem((item) => {
      item.setTitle("Add child").setIcon("plus").onClick(() => {
        this.addChildNode(node.id);
      });
    });
    if (node.id !== "root") {
      menu.addItem((item) => {
        item.setTitle("Delete").setIcon("trash").onClick(() => {
          this.deleteNode(node.id);
        });
      });
    }
    menu.addSeparator();
    menu.addItem((item) => {
      item.setTitle("Rename").setIcon("pencil").onClick(() => {
        this.pendingContextMenuRename = node;
      });
    });
    menu.addItem((item) => {
      item.setTitle("Search & link note").setIcon("search").onClick(() => {
        this.openNoteSearch();
      });
    });
    menu.addItem((item) => {
      item.setTitle("Create note from node").setIcon("file-plus").onClick(() => {
        void this.createNoteFromNode();
      });
    });
    menu.addItem((item) => {
      item.setTitle("Open linked note").setIcon("file-text").onClick(() => {
        void this.openLinkedNote();
      });
    });
    menu.showAtPosition({ x, y });
    menu.onHide(() => {
      requestAnimationFrame(() => {
        if (this.pendingContextMenuRename) {
          const target = this.pendingContextMenuRename;
          this.pendingContextMenuRename = null;
          this.editNode(target);
          return;
        }
        if (!this.isEditing) {
          this.focusContainer();
        }
      });
    });
  }
  updateTheme(theme) {
    const container = this.contentEl;
    if (container) {
      container.classList.remove("theme-default", "theme-vibrant", "theme-contrast");
      container.classList.add(`theme-${theme}`);
    }
    this.render();
  }
  createGhostNode(node, width) {
    this.ghostNode = document.createElementNS("http://www.w3.org/2000/svg", "g");
    this.ghostNode.classList.add("mindmap-ghost-node");
    this.ghostNode.setCssProps({ "opacity": "0.7", "pointer-events": "none" });
    const rect = document.createElementNS("http://www.w3.org/2000/svg", "rect");
    rect.setAttribute("rx", "20");
    rect.setAttribute("ry", "20");
    rect.setAttribute("width", width.toString());
    rect.setAttribute("height", "40");
    rect.setAttribute("fill", "var(--interactive-accent)");
    rect.setAttribute("stroke", "var(--interactive-accent)");
    rect.setAttribute("stroke-width", "2");
    const text = document.createElementNS("http://www.w3.org/2000/svg", "text");
    text.setAttribute("x", (width / 2).toString());
    text.setAttribute("y", "25");
    text.setAttribute("text-anchor", "middle");
    text.classList.add("mindmap-node-text");
    text.setCssProps({ "fill": "var(--text-on-accent)" });
    text.textContent = node.text.length > 20 ? node.text.substring(0, 20) + "..." : node.text;
    this.ghostNode.appendChild(rect);
    this.ghostNode.appendChild(text);
    this.g.appendChild(this.ghostNode);
  }
  clientToMap(clientX, clientY) {
    const svgRect = this.svg.getBoundingClientRect();
    return {
      x: (clientX - svgRect.left - this.panX) / this.zoom,
      y: (clientY - svgRect.top - this.panY) / this.zoom
    };
  }
  resolveDropMode(node, relativeX, relativeY, width, height = _MindMapView.NODE_HEIGHT) {
    if (node.id === "root") {
      if (relativeX > width * 0.6)
        return "child";
      return "replace";
    }
    if (relativeY < height * 0.3)
      return "above";
    if (relativeY > height * 0.7)
      return "below";
    if (relativeX > width * 0.72)
      return "child";
    return "replace";
  }
  getDropModeForPoint(node, mapX, mapY) {
    var _a, _b;
    const width = this.getNodeWidth(node.text);
    const nx = (_a = node.x) != null ? _a : 0;
    const ny = (_b = node.y) != null ? _b : 0;
    const height = _MindMapView.NODE_HEIGHT;
    const relX = mapX - nx;
    const relY = mapY - ny;
    const gap = _MindMapView.SIBLING_DROP_GAP;
    if (node.id !== "root") {
      if (relX >= 0 && relX <= width) {
        if (relY >= -gap && relY < 0)
          return "above";
        if (relY > height && relY <= height + gap)
          return "below";
      }
    }
    if (relX >= 0 && relX <= width && relY >= 0 && relY <= height) {
      return this.resolveDropMode(node, relX, relY, width, height);
    }
    if (relX > width && relX <= width + 80 && relY >= 0 && relY <= height) {
      return "child";
    }
    return null;
  }
  findDropTargetAt(clientX, clientY, excludeNodeId) {
    const { x: mapX, y: mapY } = this.clientToMap(clientX, clientY);
    let best = null;
    const visit = (node) => {
      var _a, _b;
      if (excludeNodeId) {
        if (node.id === excludeNodeId)
          return;
        if (this.isDescendant(excludeNodeId, node))
          return;
      }
      const mode = this.getDropModeForPoint(node, mapX, mapY);
      if (mode) {
        const width = this.getNodeWidth(node.text);
        const cx = ((_a = node.x) != null ? _a : 0) + width / 2;
        const cy = ((_b = node.y) != null ? _b : 0) + _MindMapView.NODE_HEIGHT / 2;
        const dist = Math.hypot(mapX - cx, mapY - cy);
        if (!best || dist < best.dist) {
          best = { node, mode, dist };
        }
      }
      if (!node.collapsed) {
        node.children.forEach(visit);
      }
    };
    visit(this.mindMapData.root);
    return best ? { node: best.node, mode: best.mode } : null;
  }
  handleExternalDrop(e, node, dropMode) {
    var _a, _b;
    let file = null;
    const dragManager = this.app.dragManager;
    if (dragManager) {
      const context = dragManager.viewDragContext || dragManager.activeDrag;
      if (context && context.file instanceof import_obsidian.TFile) {
        file = context.file;
      } else if (dragManager.draggable && dragManager.draggable.file instanceof import_obsidian.TFile) {
        file = dragManager.draggable.file;
      }
    }
    if (!file && e.dataTransfer) {
      const textData = e.dataTransfer.getData("text/plain");
      if (textData) {
        let linkPath = textData.replace(/^\[\[/, "").replace(/\]\]$/, "").replace(/^\[.*\]\((.*)\)$/, "$1").split("|")[0].split("#")[0].trim();
        const abstractFile = this.app.metadataCache.getFirstLinkpathDest(linkPath, ((_a = this.file) == null ? void 0 : _a.path) || "");
        if (abstractFile instanceof import_obsidian.TFile) {
          file = abstractFile;
        } else {
          const fileByPath = this.app.vault.getAbstractFileByPath(linkPath);
          if (fileByPath instanceof import_obsidian.TFile) {
            file = fileByPath;
          }
        }
      }
    }
    if (file) {
      this.insertDroppedText(node, `[[${file.basename}]]`, dropMode);
    } else {
      const textData = (_b = e.dataTransfer) == null ? void 0 : _b.getData("text/plain");
      if (textData && textData.length < 200) {
        this.insertDroppedText(node, textData, dropMode);
      }
    }
  }
  insertDroppedText(targetNode, text, dropMode) {
    if (dropMode === "replace") {
      this.pushHistory();
      targetNode.text = text;
      this.render();
      void this.saveMindMap(true);
      return;
    }
    if (dropMode === "child") {
      this.addChildNode(targetNode.id, text);
      return;
    }
    const parent = this.findParentNode(this.mindMapData.root, targetNode.id);
    if (!parent)
      return;
    this.pushHistory();
    const newNode = {
      id: `${Date.now()}-${Math.random().toString(36).substring(2, 7)}`,
      text,
      children: [],
      parent: parent.id
    };
    const targetIndex = parent.children.findIndex((n) => n.id === targetNode.id);
    const insertIndex = dropMode === "above" ? targetIndex : targetIndex + 1;
    parent.children.splice(insertIndex, 0, newNode);
    this.selectedNodeId = newNode.id;
    this.selectedNodeIds.clear();
    this.selectedNodeIds.add(newNode.id);
    this.render();
    this.scrollSelectionIntoView();
    void this.saveMindMap(true);
  }
  updateDragTarget(mapX, mapY) {
    if (!this.draggedNodeId)
      return;
    const svgRect = this.svg.getBoundingClientRect();
    const clientX = svgRect.left + this.panX + mapX * this.zoom;
    const clientY = svgRect.top + this.panY + mapY * this.zoom;
    const target = this.findDropTargetAt(clientX, clientY, this.draggedNodeId);
    if (target) {
      if (this.dragTargetNodeId !== target.node.id || this.dragDropMode !== target.mode) {
        this.dragTargetNodeId = target.node.id;
        this.dragDropMode = target.mode;
        this.updateVisualIndicators();
      }
    } else if (this.dragTargetNodeId) {
      this.dragTargetNodeId = null;
      this.dragDropMode = null;
      this.updateVisualIndicators();
    }
  }
  updateVisualIndicators() {
    this.svg.querySelectorAll(".drag-indicator-line").forEach((el) => {
      el.classList.remove("is-visible");
    });
    this.svg.querySelectorAll(".mindmap-node-rect").forEach((el) => {
      el.classList.remove("drag-target", "replace-target");
    });
    if (this.dragTargetNodeId && this.dragDropMode) {
      const nodeG = this.svg.querySelector(`[data-node-id="${this.dragTargetNodeId}"]`);
      if (nodeG) {
        const rect = nodeG.querySelector(".mindmap-node-rect");
        if (this.dragDropMode === "child") {
          if (rect)
            rect.classList.add("drag-target");
          const indicator = nodeG.querySelector(".indicator-child");
          if (indicator instanceof SVGElement)
            indicator.classList.add("is-visible");
        } else if (this.dragDropMode === "above") {
          const indicator = nodeG.querySelector(".indicator-above");
          if (indicator instanceof SVGElement)
            indicator.classList.add("is-visible");
        } else if (this.dragDropMode === "below") {
          const indicator = nodeG.querySelector(".indicator-below");
          if (indicator instanceof SVGElement)
            indicator.classList.add("is-visible");
        } else if (this.dragDropMode === "replace") {
          if (rect)
            rect.classList.add("replace-target");
        }
      }
    }
  }
  isDescendant(parentId, node) {
    let current = this.findParentNode(this.mindMapData.root, node.id);
    while (current) {
      if (current.id === parentId)
        return true;
      current = this.findParentNode(this.mindMapData.root, current.id);
    }
    return false;
  }
  moveNode(nodeId, targetId, mode) {
    const idsToMove = this.selectedNodeIds.has(nodeId) ? Array.from(this.selectedNodeIds) : [nodeId];
    const firstId = idsToMove[0];
    const oldParent = this.findParentNode(this.mindMapData.root, firstId);
    if (oldParent) {
      this.pushHistory();
      if (mode === "replace" && idsToMove.length === 1) {
        const node = this.findNodeById(this.mindMapData.root, firstId);
        const targetNode = this.findNodeById(this.mindMapData.root, targetId);
        if (node && targetNode) {
          const tempText = node.text;
          node.text = targetNode.text;
          targetNode.text = tempText;
          this.render();
          void this.saveMindMap(true);
        }
        return;
      }
      const nodesToMove = [];
      for (const id of idsToMove) {
        const n = this.findNodeById(this.mindMapData.root, id);
        if (n) {
          const p = this.findParentNode(this.mindMapData.root, id);
          if (p) {
            p.children = p.children.filter((child) => child.id !== id);
          }
          nodesToMove.push(n);
        }
      }
      if (mode === "child") {
        const newParent = this.findNodeById(this.mindMapData.root, targetId);
        if (newParent) {
          for (const node of nodesToMove) {
            node.parent = targetId;
            newParent.children.push(node);
          }
        }
      } else {
        const targetParent = this.findParentNode(this.mindMapData.root, targetId);
        if (targetParent) {
          const targetIndex = targetParent.children.findIndex((n) => n.id === targetId);
          const insertIndex = mode === "above" ? targetIndex : targetIndex + 1;
          for (let i = 0; i < nodesToMove.length; i++) {
            const node = nodesToMove[i];
            node.parent = targetParent.id;
            targetParent.children.splice(insertIndex + i, 0, node);
          }
        }
      }
      this.render();
      void this.saveMindMap(true);
    }
  }
  pushHistory() {
    const state = JSON.stringify(this.mindMapData);
    if (this.historyStack.length > 0 && this.historyStack[this.historyStack.length - 1] === state)
      return;
    this.historyStack.push(state);
    if (this.historyStack.length > 50)
      this.historyStack.shift();
  }
  undo() {
    if (this.historyStack.length === 0)
      return;
    const prevState = this.historyStack.pop();
    if (prevState) {
      this.mindMapData = JSON.parse(prevState);
      this.render();
      void this.saveMindMap(true);
      new import_obsidian.Notice("Undo");
    }
  }
  async saveMindMap(isAutoSave = false) {
    if (this.file) {
      this.requestSave();
      if (!isAutoSave)
        new import_obsidian.Notice("Mind map saved.");
      return;
    }
    if (!isAutoSave) {
      const rootNode = this.mindMapData.root;
      const defaultName = rootNode.text.replace(/[/\\?%*:|"<>]/g, "-").trim() || "Untitled";
      new SaveModal(this.app, defaultName, (fileName) => {
        void this.performSave(fileName, false);
      }).open();
    } else {
      const rootNode = this.mindMapData.root;
      const fileName = rootNode.text.replace(/[/\\?%*:|"<>]/g, "-").trim() || "Untitled";
      await this.performSave(fileName, true);
    }
  }
  async performSave(fileName, isAutoSave) {
    const folder = this.settings.exportFolder;
    await this.ensureFolderExists(folder);
    const baseName = fileName.replace(/\.mindmap$/, "");
    const fullFileName = `${baseName}.mindmap`;
    const path = folder ? `${folder}/${fullFileName}` : fullFileName;
    const content = this.getViewData();
    try {
      const existingFile = this.app.vault.getAbstractFileByPath(path);
      if (existingFile instanceof import_obsidian.TFile) {
        await this.app.vault.modify(existingFile, content);
      } else {
        await this.app.vault.create(path, content);
      }
      if (!isAutoSave) {
        new import_obsidian.Notice(`Mind map saved to ${path}`);
        const newFile = this.app.vault.getAbstractFileByPath(path);
        if (newFile instanceof import_obsidian.TFile) {
          await this.app.workspace.getLeaf(false).openFile(newFile);
        }
      }
    } catch (e) {
      if (!isAutoSave)
        new import_obsidian.Notice(`Error saving: ${e.message}`);
    }
  }
  render() {
    if (this.currentTooltip) {
      this.currentTooltip.remove();
      this.currentTooltip = null;
    }
    if (!this.g)
      return;
    if (this.editInputEl) {
      this.teardownEditInput();
    }
    this.g.innerHTML = "";
    this.calculateLayout(this.mindMapData.root, 100, 300);
    this.renderConnections(this.mindMapData.root);
    this.renderNodes(this.mindMapData.root);
    this.updateTransform();
  }
  calculateSubtreeHeight(node) {
    if (node.children.length === 0 || node.collapsed)
      return 60;
    let totalHeight = 0;
    node.children.forEach((child) => {
      totalHeight += this.calculateSubtreeHeight(child);
    });
    totalHeight += (node.children.length - 1) * 30;
    return Math.max(60, totalHeight);
  }
  calculateLayout(node, x, y) {
    node.x = x;
    node.y = y;
    if (node.children.length === 0 || node.collapsed)
      return;
    const nodeWidth = this.getNodeWidth(node.text);
    const nextX = x + nodeWidth + 80;
    const totalSubtreeHeight = this.calculateSubtreeHeight(node);
    let currentY = y - totalSubtreeHeight / 2;
    node.children.forEach((child) => {
      const childSubtreeHeight = this.calculateSubtreeHeight(child);
      const childY = currentY + childSubtreeHeight / 2;
      this.calculateLayout(child, nextX, childY);
      currentY += childSubtreeHeight + 30;
    });
  }
  renderNodes(node) {
    this.renderNode(node);
    if (!node.collapsed) {
      node.children.forEach((child) => this.renderNodes(child));
    }
  }
  renderConnections(node) {
    if (node.collapsed)
      return;
    node.children.forEach((child) => {
      var _a, _b, _c, _d;
      const path = document.createElementNS("http://www.w3.org/2000/svg", "path");
      const nodeWidth = this.getNodeWidth(node.text);
      const x1 = ((_a = node.x) != null ? _a : 0) + nodeWidth;
      const y1 = ((_b = node.y) != null ? _b : 0) + 20;
      const x2 = (_c = child.x) != null ? _c : 0;
      const y2 = ((_d = child.y) != null ? _d : 0) + 20;
      const cp1x = x1 + (x2 - x1) / 2;
      const cp2x = x1 + (x2 - x1) / 2;
      const d = `M ${x1} ${y1} C ${cp1x} ${y1}, ${cp2x} ${y2}, ${x2} ${y2}`;
      path.setAttribute("d", d);
      path.classList.add("mindmap-connection");
      this.g.appendChild(path);
      this.renderConnections(child);
    });
  }
  getNodeWidth(text) {
    const maxLength = this.settings.maxNodeLength;
    const padding = 40;
    const displayText = text.length > maxLength
      ? text.substring(0, maxLength) + "..."
      : text;
    this.textMeasureEl.textContent = displayText;
    return Math.max(120, Math.ceil(this.textMeasureEl.getComputedTextLength()) + padding);
  }
  renderNode(node) {
    const nodeG = document.createElementNS("http://www.w3.org/2000/svg", "g");
    const nodeWidth = this.getNodeWidth(node.text);
    nodeG.setAttribute("transform", `translate(${node.x}, ${node.y})`);
    nodeG.setAttribute("data-node-id", node.id);
    if (node.children.length > 0) {
      const toggleBtn = document.createElementNS("http://www.w3.org/2000/svg", "circle");
      toggleBtn.setAttribute("cx", (nodeWidth + 10).toString());
      toggleBtn.setAttribute("cy", "20");
      toggleBtn.setAttribute("r", "8");
      toggleBtn.classList.add("mindmap-node-toggle");
      nodeG.appendChild(toggleBtn);
      const toggleSymbol = document.createElementNS("http://www.w3.org/2000/svg", "text");
      toggleSymbol.setAttribute("x", (nodeWidth + 10).toString());
      toggleSymbol.setAttribute("y", "23.5");
      toggleSymbol.setAttribute("text-anchor", "middle");
      toggleSymbol.classList.add("mindmap-node-toggle-symbol");
      toggleSymbol.textContent = node.collapsed ? "+" : "-";
      nodeG.appendChild(toggleSymbol);
      const hitArea = document.createElementNS("http://www.w3.org/2000/svg", "circle");
      hitArea.setAttribute("cx", (nodeWidth + 10).toString());
      hitArea.setAttribute("cy", "20");
      hitArea.setAttribute("r", "15");
      hitArea.setAttribute("fill", "white");
      hitArea.setAttribute("fill-opacity", "0");
      hitArea.setCssProps({ "cursor": "pointer" });
      this.registerDomEvent(hitArea, "pointerdown", (e) => {
        e.preventDefault();
        e.stopPropagation();
        node.collapsed = !node.collapsed;
        this.render();
        void this.saveMindMap(true);
      });
      nodeG.appendChild(hitArea);
    }
    this.registerDomEvent(nodeG, "contextmenu", (e) => {
      e.preventDefault();
      e.stopPropagation();
      this.openNodeContextMenu(node, e.clientX, e.clientY);
    });
    this.registerDomEvent(nodeG, "click", (e) => {
      e.stopPropagation();
      if (this.suppressNextClick) {
        this.suppressNextClick = false;
        return;
      }
      this.selectNode(node.id, e.ctrlKey || e.metaKey || e.shiftKey);
    });
    this.registerDomEvent(nodeG, "dblclick", (e) => {
      e.stopPropagation();
      const wikiLinkMatch = node.text.match(/\[\[([^\]|]+)(?:\|[^\]]+)?\]\]/);
      if (wikiLinkMatch) {
        const fileName = wikiLinkMatch[1];
        const file = this.app.metadataCache.getFirstLinkpathDest(fileName, "");
        if (file instanceof import_obsidian.TFile) {
          void this.app.workspace.getLeaf("tab").openFile(file);
          return;
        }
      }
      this.editNode(node);
    });
    this.registerDomEvent(nodeG, "pointerdown", (e) => {
      if (e.button !== 0)
        return;
      e.stopPropagation();
      const container = this.containerEl.querySelector(".mindmap-svg-container");
      if (container instanceof HTMLElement) {
        container.focus({ preventScroll: true });
      }
      this.selectNode(node.id, e.ctrlKey || e.metaKey || e.shiftKey);
      const useLongPress = e.pointerType === "touch" || e.pointerType === "pen";
      let longPressTimer = null;
      let cancelLongPress = null;
      if (useLongPress) {
        longPressTimer = window.setTimeout(() => {
          longPressTimer = null;
          if (!this.isInternalDragging) {
            this.suppressNextClick = true;
            this.openNodeContextMenu(node, e.clientX, e.clientY);
          }
        }, _MindMapView.LONG_PRESS_MS);
        cancelLongPress = () => {
          if (longPressTimer !== null) {
            window.clearTimeout(longPressTimer);
            longPressTimer = null;
          }
        };
        const onLongPressPointerMove = (moveEvent) => {
          const dx = moveEvent.clientX - e.clientX;
          const dy = moveEvent.clientY - e.clientY;
          if (Math.abs(dx) > _MindMapView.LONG_PRESS_MOVE_THRESHOLD || Math.abs(dy) > _MindMapView.LONG_PRESS_MOVE_THRESHOLD) {
            cancelLongPress();
          }
        };
        const onLongPressPointerUp = () => {
          cancelLongPress();
          window.removeEventListener("pointermove", onLongPressPointerMove);
          window.removeEventListener("pointerup", onLongPressPointerUp);
          window.removeEventListener("pointercancel", onLongPressPointerUp);
        };
        window.addEventListener("pointermove", onLongPressPointerMove);
        window.addEventListener("pointerup", onLongPressPointerUp);
        window.addEventListener("pointercancel", onLongPressPointerUp);
      }
      if (node.id === "root")
        return;
      const rectBounds = nodeG.getBoundingClientRect();
      const clickOffsetX = e.clientX - rectBounds.left;
      const clickOffsetY = e.clientY - rectBounds.top;
      this.draggedNodeId = node.id;
      this.dragStartX = e.clientX;
      this.dragStartY = e.clientY;
      this.isInternalDragging = false;
      const onPointerMove = (moveEvent) => {
        const dx = moveEvent.clientX - this.dragStartX;
        const dy = moveEvent.clientY - this.dragStartY;
        if (!this.isInternalDragging && (Math.abs(dx) > 5 || Math.abs(dy) > 5)) {
          cancelLongPress == null ? void 0 : cancelLongPress();
          this.isInternalDragging = true;
          this.createGhostNode(node, nodeWidth);
        }
        if (this.isInternalDragging && this.ghostNode) {
          const svgRect = this.svg.getBoundingClientRect();
          const mapX = (moveEvent.clientX - svgRect.left - this.panX) / this.zoom;
          const mapY = (moveEvent.clientY - svgRect.top - this.panY) / this.zoom;
          const ghostX = mapX - clickOffsetX / this.zoom;
          const ghostY = mapY - clickOffsetY / this.zoom;
          this.ghostNode.setAttribute("transform", `translate(${ghostX}, ${ghostY}) scale(0.9)`);
          this.updateDragTarget(mapX, mapY);
        }
      };
      const onPointerUp = (_upEvent) => {
        window.removeEventListener("pointermove", onPointerMove);
        window.removeEventListener("pointerup", onPointerUp);
        if (this.isInternalDragging) {
          if (this.dragTargetNodeId && this.draggedNodeId && this.dragTargetNodeId !== this.draggedNodeId && this.dragDropMode) {
            this.moveNode(this.draggedNodeId, this.dragTargetNodeId, this.dragDropMode);
          }
          if (this.ghostNode) {
            if (this.ghostNode.parentNode) {
              this.g.removeChild(this.ghostNode);
            }
            this.ghostNode = null;
          }
          this.dragTargetNodeId = null;
          this.dragDropMode = null;
          this.render();
        }
        this.draggedNodeId = null;
        this.isInternalDragging = false;
      };
      window.addEventListener("pointermove", onPointerMove);
      window.addEventListener("pointerup", onPointerUp);
    });
    const rect = document.createElementNS("http://www.w3.org/2000/svg", "rect");
    const nodeStyle = this.settings.nodeStyle;
    const rx = nodeStyle === "pill" ? "20" : "4";
    rect.setAttribute("rx", rx);
    rect.setAttribute("ry", rx);
    rect.setAttribute("width", nodeWidth.toString());
    rect.setAttribute("height", "40");
    rect.classList.add("mindmap-node-rect");
    rect.setCssProps({ "pointer-events": "all" });
    if (this.selectedNodeIds.has(node.id)) {
      rect.classList.add("is-selected");
    }
    const text = document.createElementNS("http://www.w3.org/2000/svg", "text");
    text.setAttribute("x", (nodeWidth / 2).toString());
    text.setAttribute("y", "25");
    text.setAttribute("text-anchor", "middle");
    text.setCssProps({ "pointer-events": "none" });
    const maxLength = this.settings.maxNodeLength;
    if (node.text.length > maxLength) {
      text.textContent = node.text.substring(0, maxLength) + "...";
    } else {
      text.textContent = node.text;
    }
    text.classList.add("mindmap-node-text");
    if (this.settings.showHoverPreview && node.text.length > maxLength) {
      this.registerDomEvent(nodeG, "mouseenter", (e) => {
        if (this.currentTooltip)
          this.currentTooltip.remove();
        this.currentTooltip = document.body.createEl("div", { cls: "mindmap-tooltip", text: node.text });
        this.currentTooltip.setCssProps({
          "left": `${e.clientX + 15}px`,
          "top": `${e.clientY + 15}px`
        });
        const onMouseMove = (moveEvent) => {
          if (this.currentTooltip) {
            this.currentTooltip.setCssProps({
              "left": `${moveEvent.clientX + 15}px`,
              "top": `${moveEvent.clientY + 15}px`
            });
          }
        };
        const onMouseLeave = () => {
          if (this.currentTooltip) {
            this.currentTooltip.remove();
            this.currentTooltip = null;
          }
          window.removeEventListener("mousemove", onMouseMove);
          nodeG.removeEventListener("mouseleave", onMouseLeave);
        };
        window.addEventListener("mousemove", onMouseMove);
        nodeG.addEventListener("mouseleave", onMouseLeave);
      });
    }
    nodeG.appendChild(rect);
    nodeG.appendChild(text);
    const childPath = document.createElementNS("http://www.w3.org/2000/svg", "path");
    const r = 24;
    const cx = nodeWidth - 20;
    const cy = 20;
    const startAngle = -Math.PI / 12;
    const endAngle = Math.PI / 12;
    const d = `M ${cx + r * Math.cos(startAngle)},${cy + r * Math.sin(startAngle)} A ${r},${r} 0 0 1 ${cx + r * Math.cos(endAngle)},${cy + r * Math.sin(endAngle)}`;
    childPath.setAttribute("d", d);
    childPath.setAttribute("fill", "none");
    childPath.classList.add("drag-indicator-line", "indicator-child");
    const aboveLine = document.createElementNS("http://www.w3.org/2000/svg", "line");
    const lineLen = 80;
    aboveLine.setAttribute("x1", (nodeWidth / 2 - lineLen / 2).toString());
    aboveLine.setAttribute("x2", (nodeWidth / 2 + lineLen / 2).toString());
    aboveLine.setAttribute("y1", (-_MindMapView.SIBLING_DROP_GAP / 2).toString());
    aboveLine.setAttribute("y2", (-_MindMapView.SIBLING_DROP_GAP / 2).toString());
    aboveLine.classList.add("drag-indicator-line", "indicator-above");
    const belowLine = document.createElementNS("http://www.w3.org/2000/svg", "line");
    belowLine.setAttribute("x1", (nodeWidth / 2 - lineLen / 2).toString());
    belowLine.setAttribute("x2", (nodeWidth / 2 + lineLen / 2).toString());
    belowLine.setAttribute("y1", (_MindMapView.NODE_HEIGHT + _MindMapView.SIBLING_DROP_GAP / 2).toString());
    belowLine.setAttribute("y2", (_MindMapView.NODE_HEIGHT + _MindMapView.SIBLING_DROP_GAP / 2).toString());
    belowLine.classList.add("drag-indicator-line", "indicator-below");
    nodeG.appendChild(childPath);
    nodeG.appendChild(aboveLine);
    nodeG.appendChild(belowLine);
    this.g.appendChild(nodeG);
  }
  /** Align edit overlay to the rendered node rect (stable across pan/zoom). */
  positionEditInput(input, node) {
    var _a, _b, _c;
    const container = this.svgContainerEl;
    if (!container)
      return;
    const nodeEl = (_a = this.svg) == null ? void 0 : _a.querySelector(`[data-node-id="${node.id}"]`);
    if (nodeEl instanceof SVGGElement) {
      const nodeBounds = nodeEl.getBoundingClientRect();
      const containerBounds = container.getBoundingClientRect();
      const height = nodeBounds.height > 0 ? nodeBounds.height : _MindMapView.NODE_HEIGHT * this.zoom;
      input.setCssProps({
        "position": "absolute",
        "left": `${nodeBounds.left - containerBounds.left}px`,
        "top": `${nodeBounds.top - containerBounds.top}px`,
        "width": `${nodeBounds.width}px`,
        "height": `${height}px`,
        "font-size": `${Math.max(16, 14 * (height / _MindMapView.NODE_HEIGHT))}px`,
        "z-index": "20"
      });
      return;
    }
    const nodeWidth = this.getNodeWidth(node.text);
    input.setCssProps({
      "position": "absolute",
      "left": `${this.panX + ((_b = node.x) != null ? _b : 0) * this.zoom}px`,
      "top": `${this.panY + ((_c = node.y) != null ? _c : 0) * this.zoom}px`,
      "width": `${nodeWidth * this.zoom}px`,
      "height": `${_MindMapView.NODE_HEIGHT * this.zoom}px`,
      "font-size": `${Math.max(16, 14 * this.zoom)}px`,
      "z-index": "20"
    });
  }
  teardownEditInput() {
    var _a, _b;
    if (this.editViewportResizeHandler) {
      (_a = window.visualViewport) == null ? void 0 : _a.removeEventListener("resize", this.editViewportResizeHandler);
      this.editViewportResizeHandler = null;
    }
    if ((_b = this.editInputEl) == null ? void 0 : _b.parentNode) {
      this.editInputEl.parentNode.removeChild(this.editInputEl);
    }
    this.editInputEl = null;
    this.isEditing = false;
  }
  editNode(node, fallbackOnEmpty) {
    var _a;
    const container = this.containerEl.querySelector(".mindmap-svg-container");
    if (!(container instanceof HTMLElement))
      return;
    this.teardownEditInput();
    this.isEditing = true;
    const input = document.createElement("input");
    input.type = "text";
    input.value = node.text;
    input.classList.add("mindmap-edit-input");
    input.setAttribute("autocomplete", "off");
    input.setAttribute("autocorrect", "off");
    input.setAttribute("autocapitalize", "off");
    input.setAttribute("spellcheck", "false");
    container.appendChild(input);
    this.editInputEl = input;
    this.ensureNodeInView(node.id);
    this.positionEditInput(input, node);
    this.editViewportResizeHandler = () => {
      this.ensureNodeInView(node.id);
      if (this.editInputEl)
        this.positionEditInput(this.editInputEl, node);
    };
    (_a = window.visualViewport) == null ? void 0 : _a.addEventListener("resize", this.editViewportResizeHandler);
    const editOpenedAt = Date.now();
    input.focus({ preventScroll: true });
    input.select();
    const save = async () => {
      if (!this.isEditing)
        return;
      this.teardownEditInput();
      this.pushHistory();
      const oldText = node.text;
      let newText = input.value;
      if (newText.trim() === "" && fallbackOnEmpty) {
        newText = fallbackOnEmpty;
      }
      const oldWikiMatch = oldText.match(/\[\[([^\]|]+)(?:\|[^\]]+)?\]\]/);
      const newWikiMatch = newText.match(/\[\[([^\]|]+)(?:\|[^\]]+)?\]\]/);
      if (oldWikiMatch && newWikiMatch) {
        const oldFileName = oldWikiMatch[1];
        const newFileName = newWikiMatch[1];
        if (oldFileName !== newFileName) {
          const file = this.app.metadataCache.getFirstLinkpathDest(oldFileName, "");
          if (file instanceof import_obsidian.TFile) {
            this.plugin.isInternalRenaming = true;
            try {
              const folder = file.parent ? file.parent.path : "";
              const newPath = folder ? `${folder}/${newFileName}.md` : `${newFileName}.md`;
              if (newPath !== file.path) {
                const destinationFile = this.app.vault.getAbstractFileByPath(newPath);
                if (destinationFile) {
                  new import_obsidian.Notice(`Cannot rename note: "${newFileName}.md" already exists.`);
                } else {
                  await this.app.vault.rename(file, newPath);
                }
              }
            } catch (e) {
              if (!e.message.includes("already exists")) {
                new import_obsidian.Notice(`Failed to rename linked note: ${e.message}`);
              }
            } finally {
              setTimeout(() => {
                this.plugin.isInternalRenaming = false;
              }, 100);
            }
          }
        }
      }
      node.text = newText;
      this.render();
      void this.saveMindMap(true);
      setTimeout(() => this.focusContainer(), 50);
    };
    const cancel = () => {
      if (!this.isEditing)
        return;
      this.teardownEditInput();
      this.render();
      setTimeout(() => this.focusContainer(), 50);
    };
    input.addEventListener("blur", () => {
      if (Date.now() - editOpenedAt < 300) {
        requestAnimationFrame(() => {
          if (this.editInputEl === input && this.isEditing) {
            input.focus({ preventScroll: true });
          }
        });
        return;
      }
      if (this.isEditing)
        void save();
    });
    input.addEventListener("keydown", (e) => {
      if (e.key === "Enter" || e.key === "Tab") {
        e.preventDefault();
        e.stopPropagation();
        e.stopImmediatePropagation();
        this.suppressHotkeysUntil = Date.now() + 150;
        void save();
      } else if (e.key === "Escape") {
        e.preventDefault();
        e.stopPropagation();
        e.stopImmediatePropagation();
        this.suppressHotkeysUntil = Date.now() + 150;
        cancel();
      }
    });
  }
  async onClose() {
    if (this.boundWindowKeyDown) {
      window.removeEventListener("keydown", this.boundWindowKeyDown, false);
      this.boundWindowKeyDown = null;
    }
    this.teardownEditInput();
  }
  openNoteSearch() {
    if (!this.selectedNodeId)
      return;
    const node = this.findNodeById(this.mindMapData.root, this.selectedNodeId);
    if (!node)
      return;
    new NoteSuggestModal(this.app, (file) => {
      this.pushHistory();
      node.text = `[[${file.basename}]]`;
      this.render();
      const container = this.containerEl.querySelector(".mindmap-svg-container");
      if (container instanceof HTMLElement)
        container.focus();
    }).open();
  }
  async createNoteFromNode() {
    if (!this.selectedNodeId)
      return;
    const node = this.findNodeById(this.mindMapData.root, this.selectedNodeId);
    if (!node)
      return;
    let fileName = node.text.replace(/\[\[(.*?)\]\]/, "$1").trim();
    if (!fileName)
      return;
    const folder = this.settings.exportFolder || "";
    await this.ensureFolderExists(folder);
    const path = folder ? `${folder}/${fileName}.md` : `${fileName}.md`;
    try {
      let file = this.app.vault.getAbstractFileByPath(path);
      if (!(file instanceof import_obsidian.TFile)) {
        file = await this.app.vault.create(path, "");
      }
      if (file instanceof import_obsidian.TFile) {
        this.pushHistory();
        node.text = `[[${file.basename}]]`;
        this.render();
        void this.saveMindMap(true);
        await this.app.workspace.getLeaf("tab").openFile(file);
        new import_obsidian.Notice(`New note created and linked: ${file.basename}`);
      }
    } catch (e) {
      new import_obsidian.Notice(`Error creating note: ${e.message}`);
    }
  }
  renameFile() {
    if (!this.file)
      return;
    new RenameModal(this.app, this.file.basename, (newName) => {
      var _a;
      const file = this.file;
      if (file && newName && newName !== file.basename) {
        const folderPath = (_a = file.parent) == null ? void 0 : _a.path;
        const newPath = !folderPath || folderPath === "/" ? `${newName}.mindmap` : `${folderPath}/${newName}.mindmap`;
        void this.app.vault.rename(file, newPath);
      }
      setTimeout(() => this.focusContainer(), 0);
    }).open();
  }
  async openLinkedNote() {
    if (!this.selectedNodeId)
      return;
    const node = this.findNodeById(this.mindMapData.root, this.selectedNodeId);
    if (!node)
      return;
    const wikiLinkMatch = node.text.match(/\[\[([^\]|]+)(?:\|[^\]]+)?\]\]/);
    if (wikiLinkMatch) {
      const fileName = wikiLinkMatch[1];
      const file = this.app.metadataCache.getFirstLinkpathDest(fileName, "");
      if (file instanceof import_obsidian.TFile) {
        await this.app.workspace.getLeaf("tab").openFile(file);
      } else {
        new import_obsidian.Notice(`File not found: ${fileName}`);
      }
    } else {
      new import_obsidian.Notice("No linked note found in this node.");
    }
  }
};
var MindMapView = _MindMapView;
MindMapView.LONG_PRESS_MS = 500;
MindMapView.LONG_PRESS_MOVE_THRESHOLD = 10;
MindMapView.NODE_HEIGHT = 40;
MindMapView.SIBLING_DROP_GAP = 40;
var NoteSuggestModal = class extends import_obsidian.FuzzySuggestModal {
  constructor(app, onSelect) {
    super(app);
    this.onSelect = onSelect;
  }
  getItems() {
    return this.app.vault.getMarkdownFiles();
  }
  getItemText(file) {
    return file.path;
  }
  onChooseItem(file, evt) {
    this.onSelect(file);
  }
};
var FileSuggestModal = class extends import_obsidian.FuzzySuggestModal {
  constructor(app, onSelect) {
    super(app);
    this.onSelect = onSelect;
  }
  getItems() {
    return this.app.vault.getMarkdownFiles();
  }
  getItemText(file) {
    return file.path;
  }
  onChooseItem(file, evt) {
    this.onSelect(file);
  }
};
var RenameModal = class extends import_obsidian.Modal {
  constructor(app, currentName, onRename) {
    super(app);
    this.newName = currentName;
    this.onRename = onRename;
  }
  onOpen() {
    const { contentEl } = this;
    new import_obsidian.Setting(contentEl).setName("Rename mind map").setHeading();
    new import_obsidian.Setting(contentEl).setName("New name").addText(
      (text) => text.setValue(this.newName).onChange((value) => this.newName = value)
    );
    new import_obsidian.Setting(contentEl).addButton(
      (btn) => btn.setButtonText("Rename").setCta().onClick(() => {
        void this.onRename(this.newName);
        this.close();
      })
    );
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
